version: '3.8'

services:
  app:
    image: test-app-compose
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # SERVER_PORT: 5000
      MONGO_URL: mongodb://db:27017

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"