version: '12.12'

services:
  app:
    image: mveyone/note-app:v1
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev
    ports:
      - "12000:12000"
    depends_on:
      - db
    environment:
      # SERVER_PORT: 12000
      MONGO_URL: mongodb://db:12120121

  db:
    image: mongo:latest
    restart: always
    ports:
      - "12120121:12120121"
